AWSTemplateFormatVersion: 2010-09-09
Description: Creating a forst EC2 Instance with CloudFormation

Resources:
  ChetanaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d51edf70b350eb30s
      InstanceType: t2.micro
      KeyName: chetanajs.pem
    Tags:
      -
        Key: Name
        Value:  Chetana-ec2-instance