AWSTemplateFormatVersion: 2010-09-09
Description: Creating a first EC2 Instance with CloudFormation

Resources:
  karthikeyaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-065cf5d8a8da34dda
      InstanceType: t2.micro
      KeyName: kart.pem
    Tags:
      -
        Key: Name
        Value:  karthikeya-ec2-instance
  karthikeyaS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "karthikeya-devxpace-s3bucket"
  karthikeyaS3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: karthikeya-s3-access-policy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role to provide access to S3
      Policies:
        - PolicyName: karthikeya-read-write-s3-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - s3:GetBucketLocation
                - s3:ListAllMyBuckets
                Resource: "*"
              - Effect: Allow
                Action:
                - s3:ListBucket
                Resource:
                - arn:aws:s3:::test
              - Effect: Allow
                Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
                Resource:
                - !Sub arn:aws:s3:::${S3Bucket}
                - !Sub arn:aws:s3:::${S3Bucket}/*