AWSTemplateFormatVersion: 2010-09-09
Description: Creating a forst EC2 Instance with CloudFormation

Resources:
  khanEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02b4d0fc7fd1391b9
      InstanceType: t2.micro
      KeyName: khan-ec2.pem
    Tags:
      -
        Key: Name
        Value:  khan-ec2-instancels
        

