AWSTemplateFormatVersion: 2010-09-09
Description: Creating a forst EC2 Instance with CloudFormation

Resources:
  khanEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02b4d0fc7fd1391b9
      InstanceType: t2.micro
      KeyName: khan-ec2.pem
    Tags:
      -
        Key: Name
        Value:  khan-ec2-instancels
        
 khanS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "khan-devxpace-s3bucket"
  khanS3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: khan-s3-access-policy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role to provide access to S3
      Policies:
        - PolicyName: khan-read-write-s3-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - s3:GetBucketLocation
                - s3:ListAllMyBuckets
                Resource: "*"
              - Effect: Allow
                Action:
                - s3:ListBucket
                Resource:
                - arn:aws:s3:::test
              - Effect: Allow
                Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
                Resource:
                - !Sub arn:aws:s3:::${S3Bucket}
                - !Sub arn:aws:s3:::${S3Bucket}/*

