AWSTemplateFormatVersion: 2010-09-09
Description: Creating a forst EC2 Instance with CloudFormation

Resources:
  PoornaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9
      InstanceType: t2.micro
      KeyName: linux-tutorial03.pem
    Tags:
      -
        Key: Name
        Value:  poorna-ec2-instance

  supriyaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02b4d0fc7fd1391b9
      InstanceType: t2.micro
      KeyName: supriya.pem
    Tags:
      -
        Key: Name
        Value:  supriya-ec2-instance