AWSTemplateFormatVersion: 2010-09-09
Description: Creating a forst EC2 Instance with CloudFormation

Resources:
  RajaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04e92ffd253e42a3d
      InstanceType: t2.micro
      KeyName: raja.pem
    Tags:
      -
        Key: raj
        Value:  raja-ec2-instance
RajaS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "raja-devxpace-s3bucket"
  RajaS3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: raja-s3-access-policy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role to provide access to S3
      Policies:
        - PolicyName: raja-read-write-s3-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - s3:GetBucketLocation
                - s3:ListAllMyBuckets
                Resource: "*"
              - Effect: Allow
                Action:
                - s3:ListBucket
                Resource:
                - arn:aws:s3:::test
              - Effect: Allow
                Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
                Resource:
                - !Sub arn:aws:s3:::${S3Bucket}
                - !Sub arn:aws:s3:::${S3Bucket}/*
