AWSTemplateFormatVersion: 2010-09-09
Description: Creating a forst EC2 Instance with CloudFormation

Resources:
  supriyaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bfbb74cdfd99d136
      InstanceType: t2.micro
      KeyName: supriya.pem
    Tags:
      -
        Key: Name
        Value:  supriya-ec2-instance